-- @description Dynamic Hotkeys: Context-aware ReaScript actions
-- @version 1.0
-- @author BIXI DOX
-- @assistant ChatGPT
-- @changelog
--  + init
-- @about
--   Dynamically triggers actions depending on the mouse context
--   and current selection states for items, envelopes, and automation.




--[===================================================================================================================================================================================================================================================]--
                                                                                                                                                                                                                                                       --
local r = reaper;                                                                                                                                                                                                                                      --
                                                                                                                                                                                                                                                       --
--[============================]--                                                                                                                                                                                                                     --
                                --                                                                                                                                                                                                                     --
local function nothing() end;   --                                                                                                                                                                                                                     --
                                --                                                                                                                                                                                                                     --
--[============================]--                                                                                                                                                                                                                     --
                                                                                                                                                                                                                                                       --
--[============================]--                                                                                                                                                                                                                     --
                                --                                                                                                                                                                                                                     --
local function blank()          --                                                                                                                                                                                                                     --
                                --                                                                                                                                                                                                                     --
    r.defer(nothing)            --                                                                                                                                                                                                                     --
                                --                                                                                                                                                                                                                     --
end                             --                                                                                                                                                                                                                     --
                                --                                                                                                                                                                                                                     --
--[============================]--                                                                                                                                                                                                                     --
                                                                                                                                                                                                                                                       --
                                                                                                                                                                                                                                                       --
--=== Utility Functions ===--                                                                                                                                                                                                                          --
--[[================================================================================================================================================================================================]]--                                               --
                                                                                                                                                                                                      --                                               --
--[[============================================================]]                                                                                                                                    --                                               --
--[[ Check if any automation items are selected on any envelope ]]                                                                                                                                    --                                               --
--[[============================================================]]--=========================================================]]--                                                                     --                                               --
                                                                                                                               --                                                                     --                                               --
function anySelectedAutomationItems()                                                                                          --                                                                     --                                               --
                                                                                                                               --                                                                     --                                               --
    for count_track = 0, r.CountTracks(0)-1 do                                                                                 --                                                                     --                                               --
                                                                                                                               --                                                                     --                                               --
        local get_track = r.GetTrack(0, count_track)                                                                           --                                                                     --                                               --
                                                                                                                               --                                                                     --                                               --
        for count_track_envelopes = 0, r.CountTrackEnvelopes(get_track)-1 do                                                   --                                                                     --                                               --
                                                                                                                               --                                                                     --                                               --
            local get_track_envelopes = r.GetTrackEnvelope(get_track, count_track_envelopes)                                   --                                                                     --                                               --
                                                                                                                               --                                                                     --                                               --
            for count_automation_items = 0, r.CountAutomationItems(get_track_envelopes)-1 do                                   --                                                                     --                                               --
                                                                                                                               --                                                                     --                                               --
                if r.GetSetAutomationItemInfo(get_track_envelopes, count_automation_items, "D_UISEL", 0, false) == 1 then      --                                                                     --                                               --
                                                                                                                               --                                                                     --                                               --
                    return true                                                                                                --                                                                     --                                               --
                                                                                                                               --                                                                     --                                               --
                end                                                                                                            --                                                                     --                                               --
            end                                                                                                                --                                                                     --                                               --
        end                                                                                                                    --                                                                     --                                               --
    end                                                                                                                        --                                                                     --                                               --
                                                                                                                               --                                                                     --                                               --
    return false                                                                                                               --                                                                     --                                               --
end                                                                                                                            --                                                                     --                                               --
                                                                                                                               --                                                                     --                                               --
--[[=========================================================================================================================]]--                                                                     --                                               --
                                                                                                                                                                                                      --                                               --
                                                                                                                                                                                                      --                                               --
                                                                                                                                                                                                      --                                               --
                                                                                                                                                                                                      --                                               --
--[[=========================================================]]                                                                                                                                       --                                               --
--[[Check if any envelope points are selected on any envelope]]                                                                                                                                       --                                               --
--[[=========================================================]]--====================================================--                                                                               --                                               --
                                                                                                                     --                                                                               --                                               --
function anySelectedEnvelopePoints()                                                                                 --                                                                               --                                               --
                                                                                                                     --                                                                               --                                               --
    for count_track = 0, r.CountTracks(0)-1 do                                                                       --                                                                               --                                               --
                                                                                                                     --                                                                               --                                               --
        local get_track = r.GetTrack(0, count_track)                                                                 --                                                                               --                                               --
                                                                                                                     --                                                                               --                                               --
        for count_track_envelopes = 0, r.CountTrackEnvelopes(get_track)-1 do                                         --                                                                               --                                               --
                                                                                                                     --                                                                               --                                               --
            local get_track_envelopes = r.GetTrackEnvelope(get_track, count_track_envelopes)                         --                                                                               --                                               --
                                                                                                                     --                                                                               --                                               --
            for count_envelope_points = 0, r.CountEnvelopePoints(get_track_envelopes)-1 do                           --                                                                               --                                               --
                                                                                                                     --                                                                               --                                               --
                local _, _, _, _, _, selected = r.GetEnvelopePoint(get_track_envelopes, count_envelope_points)       --                                                                               --                                               --
                                                                                                                     --                                                                               --                                               --
                if selected ~= 1 then                                                                                --                                                                               --                                               --
                                                                                                                     --                                                                               --                                               --
                    return true                                                                                      --                                                                               --                                               --
                                                                                                                     --                                                                               --                                               --
                end                                                                                                  --                                                                               --                                               --
            end                                                                                                      --                                                                               --                                               --
        end                                                                                                          --                                                                               --                                               --
    end                                                                                                              --                                                                               --                                               --
                                                                                                                     --                                                                               --                                               --
    return false                                                                                                     --                                                                               --                                               --
end                                                                                                                  --                                                                               --                                               --
                                                                                                                     --                                                                               --                                               --
--[[=================================================================================================================--                                                                               --                                               --
                                                                                                                                                                                                      --                                               --
--[[================================================================================================================================================================================================]]--                                               --
                                                                                                                                                                                                                                                       --
                                                                                                                                                                                                                                                       --
                                                                                                                                                                                                                                                       --
                                                                                                                                                                                                                                                       --
--[[=========================]]--                                                                                                                                                                                                                      --
                               --                                                                                                                                                                                                                      --
function Dynamic_Hotkeys()     --                                                                                                                                                                                                                      --
                               --                                                                                                                                                                                                                      --
--[[========================================================================================================================]]--                                                                                                                       --
                                                                                                                              --                                                                                                                       --
    local function action(id) r.Main_OnCommand(id, 0) end                                                                     --                                                                                                                       --
    local count_selected_items = r.CountSelectedMediaItems(0)                                                                 --                                                                                                                       --
    local window, segment, details = r.BR_GetMouseCursorContext()                                                             --                                                                                                                       --
                                                                                                                              --                                                                                                                       --
    --[Native Actions Variables]----------------------------------------------------------------                              --                                                                                                                       --
    local move_items_or_envelope_points_left = 40793                                                                          -- Item edit: Move items/envelope points left by grid size                                                               --
    local move_envelope_points_left = 41176                                                                                   -- Envelopes: Move selected points left a little bit                                                                     --
    local move_item_content_left = 40123                                                                                      --                                                                                                                       --
    local move_cursor_left = 40646                                                                                            -- View: Move cursor left to grid division                                                                               --
                                                                                                                              --                                                                                                                       --
    --[Script Actions Variables]----------------------------------------------------------------                              --                                                                                                                       --
    local move_time_selection_left = r.NamedCommandLookup("_RS65aa95c3f1c047e6fefb2244a2ec5288dc3f7d4a")                      -- Script: Reaper Studio & ChatGPT - Move time selection left by grid.lua                                                --
    local shorten_automation_items_end = r.NamedCommandLookup("_RSefee09cc6d46f39d8ce77ca127ab349f25b3bb44")             -- Script: Reaper Studio & ChatGPT - Automation Items - End - Shorten by grid.lua                                          --
    local shorten_items_end_length = r.NamedCommandLookup("_RS31bbec80e0dd8dbd219c87224a0f9648dbca7543")                      -- Script: me2beats_Trim sel items right edges to nearest grid divisions (decrease items length).lua                     --
    --------------------------------------------------------------------------------------------                              --                                                                                                                       --
                                                                                                                              --                                                                                                                       --
--[===============================================]--                                                                         --                                                                                                                       --
                                                   --                                                                         --                                                                                                                       --
    if window == 'ruler' then                      --                                                                         --                                                                                                                       --
                                                   --                                                                         --                                                                                                                       --
        action(move_time_selection_left)           --                                                                         --                                                                                                                       --
                                                   --                                                                         --                                                                                                                       --
--[===============================================]--                                                                         --                                                                                                                       --
                                                                                                                              --                                                                                                                       --
                                                                                                                              --                                                                                                                       --
--[=================================]--                                                                                       --                                                                                                                       --
                                     --                                                                                       --                                                                                                                       --
    elseif window == 'tcp' then      --                                                                                       --                                                                                                                       --
                                     --                                                                                       --                                                                                                                       --
        return                       --                                                                                       --                                                                                                                       --
                                     --                                                                                       --                                                                                                                       --
--[=================================]--                                                                                       --                                                                                                                       --
                                                                                                                              --                                                                                                                       --
                                                                                                                              --                                                                                                                       --
--[=============================================================]--                                                           --                                                                                                                       --
                                                                 --                                                           --                                                                                                                       --
    elseif segment == 'envelope' then                            --                                                           --                                                                                                                       --
                                                                 --                                                           --                                                                                                                       --
        --[==============================================]--     --                                                           --                                                                                                                       --
                                                          --     --                                                           --                                                                                                                       --
        if anySelectedAutomationItems() then              --     --                                                           --                                                                                                                       --
                                                          --     --                                                           --                                                                                                                       --
            action(shorten_automation_items_end)     --     --                                                           --                                                                                                                       --
                                                          --     --                                                           --                                                                                                                       --
        --[==============================================]--     --                                                           --                                                                                                                       --
                                                                 --                                                           --                                                                                                                       --
        --[==============================================]--     --                                                           --                                                                                                                       --
                                                          --     --                                                           --                                                                                                                       --
        elseif anySelectedEnvelopePoints() then           --     --                                                           --                                                                                                                       --
                                                          --     --                                                           --                                                                                                                       --
            action(move_envelope_points_left)             --     --                                                           --                                                                                                                       --
                                                          --     --                                                           --                                                                                                                       --
        --[==============================================]--     --                                                           --                                                                                                                       --
                                                                 --                                                           --                                                                                                                       --
        --[==============================================]--     --                                                           --                                                                                                                       --
                                                          --     --                                                           --                                                                                                                       --
        else                                              --     --                                                           --                                                                                                                       --
                                                          --     --                                                           --                                                                                                                       --
            return                                        --     --                                                           --                                                                                                                       --
                                                          --     --                                                           --                                                                                                                       --
        end                                               --     --                                                           --                                                                                                                       --
                                                          --     --                                                           --                                                                                                                       --
        --[==============================================]--     --                                                           --                                                                                                                       --
                                                                 --                                                           --                                                                                                                       --
--[=============================================================]--                                                           --                                                                                                                       --
                                                                                                                              --                                                                                                                       --
                                                                                                                              --                                                                                                                       --
--[==================================================================]--                                                      --                                                                                                                       --
                                                                      --                                                      --                                                                                                                       --
    elseif count_selected_items > 0 and details == 'item' then        --                                                      --                                                                                                                       --
                                                                      --                                                      --                                                                                                                       --
        local item = r.BR_GetMouseCursorContext_Item()                --                                                      --                                                                                                                       --
        local over_selected_item = r.IsMediaItemSelected(item, 0)     --                                                      --                                                                                                                       --
                                                                      --                                                      --                                                                                                                       --
        --[======================================================]--  --                                                      --                                                                                                                       --
                                                                  --  --                                                      --                                                                                                                       --
        if over_selected_item then                                --  --                                                      --                                                                                                                       --
                                                                  --  --                                                      --                                                                                                                       --
            action(move_item_content_left)                        --  --                                                      --                                                                                                                       --
                                                                  --  --                                                      --                                                                                                                       --
        --[======================================================]--  --                                                      --                                                                                                                       --
                                                                      --                                                      --                                                                                                                       --
        --[======================================================]--  --                                                      --                                                                                                                       --
                                                                  --  --                                                      --                                                                                                                       --
        else                                                      --  --                                                      --                                                                                                                       --
                                                                  --  --                                                      --                                                                                                                       --
            return                                                --  --                                                      --                                                                                                                       --
                                                                  --  --                                                      --                                                                                                                       --
        end                                                       --  --                                                      --                                                                                                                       --
                                                                  --  --                                                      --                                                                                                                       --
        --[======================================================]--  --                                                      --                                                                                                                       --
                                                                      --                                                      --                                                                                                                       --
                                                                      --                                                      --                                                                                                                       --
--[==================================================================]--                                                      --                                                                                                                       --
                                                                                                                              --                                                                                                                       --
                                                                                                                              --                                                                                                                       --
--[=====================================================================]--                                                   --                                                                                                                       --
                                                                         --                                                   --                                                                                                                       --
    elseif window == 'arrange' then                                      --                                                   --                                                                                                                       --
                                                                         --                                                   --                                                                                                                       --
        --[=========================================================]--  --                                                   --                                                                                                                       --
                                                                     --  --                                                   --                                                                                                                       --
        if count_selected_items > 0 then                             --  --                                                   --                                                                                                                       --
                                                                     --  --                                                   --                                                                                                                       --
            action(shorten_items_end_length)                         --  --                                                   --                                                                                                                       --
                                                                     --  --                                                   --                                                                                                                       --
        --[=========================================================]--  --                                                   --                                                                                                                       --
                                                                         --                                                   --                                                                                                                       --
--[=====================================================================]--                                                   --                                                                                                                       --
                                                                                                                              --                                                                                                                       --
                                                                                                                              --                                                                                                                       --
--[==================================================================]--                                                      --                                                                                                                       --
                                                                      --                                                      --                                                                                                                       --
    else                                                              --                                                      --                                                                                                                       --
                                                                      --                                                      --                                                                                                                       --
        action(move_cursor_left)                                      --                                                      --                                                                                                                       --
                                                                      --                                                      --                                                                                                                       --
    end                                                               --                                                      --                                                                                                                       --
                                                                      --                                                      --                                                                                                                       --
--[==================================================================]--                                                      --                                                                                                                       --
                                                                                                                              --                                                                                                                       --
end                                                                                                                           --                                                                                                                       --
                                                                                                                              --                                                                                                                       --
--[============]--                                                                                                            --                                                                                                                       --
                --                                                                                                            --                                                                                                                       --
blank()         --                                                                                                            --                                                                                                                       --
                --                                                                                                            --                                                                                                                       --
end             --                                                                                                            --                                                                                                                       --
                --                                                                                                            --                                                                                                                       --
--[============]--                                                                                                            --                                                                                                                       --
                                                                                                                              --                                                                                                                       --
--[[========================================================================================================================]]--                                                                                                                       --
                                                                                                                                                                                                                                                       --
--[[========================================================================================================================]]--                                                                                                                       --
                                                                                                                              --                                                                                                                       --
r.Undo_BeginBlock()                                                                                                           --                                                                                                                       --
                                                                                                                              --                                                                                                                       --
Dynamic_Hotkeys()                                                                                                             --                                                                                                                       --
                                                                                                                              --                                                                                                                       --
r.UpdateArrange()                                                                                                             --                                                                                                                       --
r.Undo_EndBlock('Zoom horizontally/vertically depending on ArrangeView/Ruler, If item/take selected, adjust volume', 2)       --                                                                                                                       --
                                                                                                                              --                                                                                                                       --
--[[========================================================================================================================]]--                                                                                                                       --
                                                                                                                                                                                                                                                       --
--[===================================================================================================================================================================================================================================================]--                                                                                                                                                                                                                                                                           