-- @description Dynamic Hotkeys: Context-aware ReaScript actions
-- @version 1.0
-- @author BIXI DOX
-- @assistant ChatGPT
-- @changelog
--  + init
-- @about
--   Dynamically triggers actions depending on the mouse context
--   and current selection states for items, envelopes, and automation.




--[===================================================================================================================================================================================================================================================]--
                                                                                                                                                                                                                                                       --
local r = reaper;                                                                                                                                                                                                                                      --
                                                                                                                                                                                                                                                       --
--[============================]--                                                                                                                                                                                                                     --
                                --                                                                                                                                                                                                                     --
local function nothing() end;   --                                                                                                                                                                                                                     --
                                --                                                                                                                                                                                                                     --
--[============================]--                                                                                                                                                                                                                     --
                                                                                                                                                                                                                                                       --
--[============================]--                                                                                                                                                                                                                     --
                                --                                                                                                                                                                                                                     --
local function blank()          --                                                                                                                                                                                                                     --
                                --                                                                                                                                                                                                                     --
    r.defer(nothing)            --                                                                                                                                                                                                                     --
                                --                                                                                                                                                                                                                     --
end                             --                                                                                                                                                                                                                     --
                                --                                                                                                                                                                                                                     --
--[============================]--                                                                                                                                                                                                                     --
                                                                                                                                                                                                                                                       --
                                                                                                                                                                                                                                                       --
--=== Utility Functions ===--                                                                                                                                                                                                                          --
--[[================================================================================================================================================================================================]]--                                               --
                                                                                                                                                                                                      --                                               --
--[[============================================================]]                                                                                                                                    --                                               --
--[[ Check if any automation items are selected on any envelope ]]                                                                                                                                    --                                               --
--[[============================================================]]--=========================================================]]--                                                                     --                                               --
                                                                                                                               --                                                                     --                                               --
function anySelectedAutomationItems()                                                                                          --                                                                     --                                               --
                                                                                                                               --                                                                     --                                               --
    for count_track = 0, r.CountTracks(0)-1 do                                                                                 --                                                                     --                                               --
                                                                                                                               --                                                                     --                                               --
        local get_track = r.GetTrack(0, count_track)                                                                           --                                                                     --                                               --
                                                                                                                               --                                                                     --                                               --
        for count_track_envelopes = 0, r.CountTrackEnvelopes(get_track)-1 do                                                   --                                                                     --                                               --
                                                                                                                               --                                                                     --                                               --
            local get_track_envelopes = r.GetTrackEnvelope(get_track, count_track_envelopes)                                   --                                                                     --                                               --
                                                                                                                               --                                                                     --                                               --
            for count_automation_items = 0, r.CountAutomationItems(get_track_envelopes)-1 do                                   --                                                                     --                                               --
                                                                                                                               --                                                                     --                                               --
                if r.GetSetAutomationItemInfo(get_track_envelopes, count_automation_items, "D_UISEL", 0, false) == 1 then      --                                                                     --                                               --
                                                                                                                               --                                                                     --                                               --
                    return true                                                                                                --                                                                     --                                               --
                                                                                                                               --                                                                     --                                               --
                end                                                                                                            --                                                                     --                                               --
            end                                                                                                                --                                                                     --                                               --
        end                                                                                                                    --                                                                     --                                               --
    end                                                                                                                        --                                                                     --                                               --
                                                                                                                               --                                                                     --                                               --
    return false                                                                                                               --                                                                     --                                               --
end                                                                                                                            --                                                                     --                                               --
                                                                                                                               --                                                                     --                                               --
--[[=========================================================================================================================]]--                                                                     --                                               --
                                                                                                                                                                                                      --                                               --
                                                                                                                                                                                                      --                                               --
                                                                                                                                                                                                      --                                               --
                                                                                                                                                                                                      --                                               --
--[[=========================================================]]                                                                                                                                       --                                               --
--[[Check if any envelope points are selected on any envelope]]                                                                                                                                       --                                               --
--[[=========================================================]]--====================================================--                                                                               --                                               --
                                                                                                                     --                                                                               --                                               --
function anySelectedEnvelopePoints()                                                                                 --                                                                               --                                               --
                                                                                                                     --                                                                               --                                               --
    for count_track = 0, r.CountTracks(0)-1 do                                                                       --                                                                               --                                               --
                                                                                                                     --                                                                               --                                               --
        local get_track = r.GetTrack(0, count_track)                                                                 --                                                                               --                                               --
                                                                                                                     --                                                                               --                                               --
        for count_track_envelopes = 0, r.CountTrackEnvelopes(get_track)-1 do                                         --                                                                               --                                               --
                                                                                                                     --                                                                               --                                               --
            local get_track_envelopes = r.GetTrackEnvelope(get_track, count_track_envelopes)                         --                                                                               --                                               --
                                                                                                                     --                                                                               --                                               --
            for count_envelope_points = 0, r.CountEnvelopePoints(get_track_envelopes)-1 do                           --                                                                               --                                               --
                                                                                                                     --                                                                               --                                               --
                local _, _, _, _, _, selected = r.GetEnvelopePoint(get_track_envelopes, count_envelope_points)       --                                                                               --                                               --
                                                                                                                     --                                                                               --                                               --
                if selected ~= 1 then                                                                                --                                                                               --                                               --
                                                                                                                     --                                                                               --                                               --
                    return true                                                                                      --                                                                               --                                               --
                                                                                                                     --                                                                               --                                               --
                end                                                                                                  --                                                                               --                                               --
            end                                                                                                      --                                                                               --                                               --
        end                                                                                                          --                                                                               --                                               --
    end                                                                                                              --                                                                               --                                               --
                                                                                                                     --                                                                               --                                               --
    return false                                                                                                     --                                                                               --                                               --
end                                                                                                                  --                                                                               --                                               --
                                                                                                                     --                                                                               --                                               --
--[[=================================================================================================================--                                                                               --                                               --
                                                                                                                                                                                                      --                                               --
--[[================================================================================================================================================================================================]]--                                               --
                                                                                                                                                                                                                                                       --
                                                                                                                                                                                                                                                       --
                                                                                                                                                                                                                                                       --
                                                                                                                                                                                                                                                       --
--[[=========================]]--                                                                                                                                                                                                                      --
                               --                                                                                                                                                                                                                      --
function Dynamic_Hotkeys()     --                                                                                                                                                                                                                      --
                               --                                                                                                                                                                                                                      --
--[[========================================================================================================================]]--                                                                                                                       --
                                                                                                                              --                                                                                                                       --
    local function action(id) r.Main_OnCommand(id, 0) end                                                                     --                                                                                                                       --
    local count_selected_items = r.CountSelectedMediaItems(0)                                                                 --                                                                                                                       --
    local window, segment, details = r.BR_GetMouseCursorContext()                                                             --                                                                                                                       --
                                                                                                                              --                                                                                                                       --
    --[Native Actions Variables]----------------------------------------------------------------                              --                                                                                                                       --
    local move_items_or_envelope_points_right = 40794                                                                         -- Item edit: Move items/envelope points right by grid size                                                              --
    local move_envelope_points_right = 41177                                                                                  --                                                                                                                       --
    local move_item_content_right = 40124                                                                                     --                                                                                                                       --
    local move_cursor_right = 40647                                                                                           -- View: Move cursor right to grid division                                                                              --
                                                                                                                              --                                                                                                                       --
    --[Script Actions Variables]----------------------------------------------------------------                              --                                                                                                                       --
    local move_time_selection_right = r.NamedCommandLookup("_RS7d3498496f439fec961be55cd769b46a7fa64ce0")            -- Script: Script: Reaper Studio & ChatGPT - Move time selection and items within it right by grid.lua                   --
    local extend_automation_items_end = r.NamedCommandLookup("_RS7157ecbc71e9940a7bf9fae989146bb08aaa031b")                   -- Script: Reaper Studio & ChatGPT - Move automation items right by grid.lua                                             --
    local extend_items_start_length = r.NamedCommandLookup("_RS03d4fe41cc2465442f8783353e07e895eb472fbd")                   -- Script: Reaper Studio & ChatGPT - Move automation items right by grid.lua                                             --
    --------------------------------------------------------------------------------------------                              --                                                                                                                       --
                                                                                                                              --                                                                                                                       --
--[===============================================]--                                                                         --                                                                                                                       --
                                                   --                                                                         --                                                                                                                       --
    if window == 'ruler' then                      --                                                                         --                                                                                                                       --
                                                   --                                                                         --                                                                                                                       --
        action(move_time_selection_right) --                                                                         --                                                                                                                       --
                                                   --                                                                         --                                                                                                                       --
--[===============================================]--                                                                         --                                                                                                                       --
                                                                                                                              --                                                                                                                       --
                                                                                                                              --                                                                                                                       --
--[=================================]--                                                                                       --                                                                                                                       --
                                     --                                                                                       --                                                                                                                       --
    elseif window == 'tcp' then      --                                                                                       --                                                                                                                       --
                                     --                                                                                       --                                                                                                                       --
        return                       --                                                                                       --                                                                                                                       --
                                     --                                                                                       --                                                                                                                       --
--[=================================]--                                                                                       --                                                                                                                       --
                                                                                                                              --                                                                                                                       --
                                                                                                                              --                                                                                                                       --
--[=============================================================]--                                                           --                                                                                                                       --
                                                                 --                                                           --                                                                                                                       --
    elseif segment == 'envelope' then                            --                                                           --                                                                                                                       --
                                                                 --                                                           --                                                                                                                       --
        --[==============================================]--     --                                                           --                                                                                                                       --
                                                          --     --                                                           --                                                                                                                       --
        if anySelectedAutomationItems() then              --     --                                                           --                                                                                                                       --
                                                          --     --                                                           --                                                                                                                       --
            action(extend_automation_items_end)           --     --                                                           --                                                                                                                       --
                                                          --     --                                                           --                                                                                                                       --
        --[==============================================]--     --                                                           --                                                                                                                       --
                                                                 --                                                           --                                                                                                                       --
        --[==============================================]--     --                                                           --                                                                                                                       --
                                                          --     --                                                           --                                                                                                                       --
        elseif anySelectedEnvelopePoints() then           --     --                                                           --                                                                                                                       --
                                                          --     --                                                           --                                                                                                                       --
            action(move_envelope_points_right)            --     --                                                           --                                                                                                                       --
                                                          --     --                                                           --                                                                                                                       --
        --[==============================================]--     --                                                           --                                                                                                                       --
                                                                 --                                                           --                                                                                                                       --
        --[==============================================]--     --                                                           --                                                                                                                       --
                                                          --     --                                                           --                                                                                                                       --
        else                                              --     --                                                           --                                                                                                                       --
                                                          --     --                                                           --                                                                                                                       --
            return                                        --     --                                                           --                                                                                                                       --
                                                          --     --                                                           --                                                                                                                       --
        end                                               --     --                                                           --                                                                                                                       --
                                                          --     --                                                           --                                                                                                                       --
        --[==============================================]--     --                                                           --                                                                                                                       --
                                                                 --                                                           --                                                                                                                       --
--[=============================================================]--                                                           --                                                                                                                       --
                                                                                                                              --                                                                                                                       --
                                                                                                                              --                                                                                                                       --
--[==================================================================]--                                                      --                                                                                                                       --
                                                                      --                                                      --                                                                                                                       --
    elseif count_selected_items > 0 and details == 'item' then        --                                                      --                                                                                                                       --
                                                                      --                                                      --                                                                                                                       --
        local item = r.BR_GetMouseCursorContext_Item()                --                                                      --                                                                                                                       --
        local over_selected_item = r.IsMediaItemSelected(item, 0)     --                                                      --                                                                                                                       --
                                                                      --                                                      --                                                                                                                       --
        --[======================================================]--  --                                                      --                                                                                                                       --
                                                                  --  --                                                      --                                                                                                                       --
        if over_selected_item then                                --  --                                                      --                                                                                                                       --
                                                                  --  --                                                      --                                                                                                                       --
            action(move_item_content_right)                       --  --                                                      --                                                                                                                       --
                                                                  --  --                                                      --                                                                                                                       --
        --[======================================================]--  --                                                      --                                                                                                                       --
                                                                      --                                                      --                                                                                                                       --
        --[======================================================]--  --                                                      --                                                                                                                       --
                                                                  --  --                                                      --                                                                                                                       --
        else                                                      --  --                                                      --                                                                                                                       --
                                                                  --  --                                                      --                                                                                                                       --
            return                                                --  --                                                      --                                                                                                                       --
                                                                  --  --                                                      --                                                                                                                       --
        end                                                       --  --                                                      --                                                                                                                       --
                                                                  --  --                                                      --                                                                                                                       --
        --[======================================================]--  --                                                      --                                                                                                                       --
                                                                      --                                                      --                                                                                                                       --
                                                                      --                                                      --                                                                                                                       --
--[==================================================================]--                                                      --                                                                                                                       --
                                                                                                                              --                                                                                                                       --
                                                                                                                              --                                                                                                                       --
--[=====================================================================]--                                                   --                                                                                                                       --
                                                                         --                                                   --                                                                                                                       --
    elseif window == 'arrange' then                                      --                                                   --                                                                                                                       --
                                                                         --                                                   --                                                                                                                       --
        --[=========================================================]--  --                                                   --                                                                                                                       --
                                                                     --  --                                                   --                                                                                                                       --
        if count_selected_items > 0 then                             --  --                                                   --                                                                                                                       --
                                                                     --  --                                                   --                                                                                                                       --
            action(extend_items_start_length)              --  --                                                   --                                                                                                                       --
                                                                     --  --                                                   --                                                                                                                       --
        --[=========================================================]--  --                                                   --                                                                                                                       --
                                                                         --                                                   --                                                                                                                       --
--[=====================================================================]--                                                   --                                                                                                                       --
                                                                                                                              --                                                                                                                       --
                                                                                                                              --                                                                                                                       --
--[==================================================================]--                                                      --                                                                                                                       --
                                                                      --                                                      --                                                                                                                       --
    else                                                              --                                                      --                                                                                                                       --
                                                                      --                                                      --                                                                                                                       --
        action(move_cursor_right)                                     --                                                      --                                                                                                                       --
                                                                      --                                                      --                                                                                                                       --
    end                                                               --                                                      --                                                                                                                       --
                                                                      --                                                      --                                                                                                                       --
--[==================================================================]--                                                      --                                                                                                                       --
                                                                                                                              --                                                                                                                       --
end                                                                                                                           --                                                                                                                       --
                                                                                                                              --                                                                                                                       --
--[============]--                                                                                                            --                                                                                                                       --
                --                                                                                                            --                                                                                                                       --
blank()         --                                                                                                            --                                                                                                                       --
                --                                                                                                            --                                                                                                                       --
end             --                                                                                                            --                                                                                                                       --
                --                                                                                                            --                                                                                                                       --
--[============]--                                                                                                            --                                                                                                                       --
                                                                                                                              --                                                                                                                       --
--[[========================================================================================================================]]--                                                                                                                       --
                                                                                                                                                                                                                                                       --
--[[========================================================================================================================]]--                                                                                                                       --
                                                                                                                              --                                                                                                                       --
r.Undo_BeginBlock()                                                                                                           --                                                                                                                       --
                                                                                                                              --                                                                                                                       --
Dynamic_Hotkeys()                                                                                                             --                                                                                                                       --
                                                                                                                              --                                                                                                                       --
r.UpdateArrange()                                                                                                             --                                                                                                                       --
r.Undo_EndBlock('Dynamic Hotkeys - right', 2)                                                                                 --                                                                                                                       --
                                                                                                                              --                                                                                                                       --
--[[========================================================================================================================]]--                                                                                                                       --
                                                                                                                                                                                                                                                       --
--[===================================================================================================================================================================================================================================================]--                                                                                                                                                                                                                                                                           