-- @description Dynamic Hotkeys: Context-aware ReaScript actions
-- @version 1.0
-- @author BIXI DOX
-- @assistant ChatGPT
-- @changelog
--  + init
-- @about
--   Dynamically triggers actions depending on the mouse context
--   and current selection states for items, envelopes, and automation.




--[===================================================================================================================================================================================================================================================]--
                                                                                                                                                                                                                                                       --
local r = reaper;                                                                                                                                                                                                                                      --
                                                                                                                                                                                                                                                       --
--[============================]--                                                                                                                                                                                                                     --
                                --                                                                                                                                                                                                                     --
local function nothing() end;   --                                                                                                                                                                                                                     --
                                --                                                                                                                                                                                                                     --
--[============================]--                                                                                                                                                                                                                     --
                                                                                                                                                                                                                                                       --
--[============================]--                                                                                                                                                                                                                     --
                                --                                                                                                                                                                                                                     --
local function blank()          --                                                                                                                                                                                                                     --
                                --                                                                                                                                                                                                                     --
    r.defer(nothing)            --                                                                                                                                                                                                                     --
                                --                                                                                                                                                                                                                     --
end                             --                                                                                                                                                                                                                     --
                                --                                                                                                                                                                                                                     --
--[============================]--                                                                                                                                                                                                                     --
                                                                                                                                                                                                                                                       --
                                                                                                                                                                                                                                                       --
--=== Utility Functions ===--                                                                                                                                                                                                                          --
--[[================================================================================================================================================================================================]]--                                               --
                                                                                                                                                                                                      --                                               --
--[[============================================================]]                                                                                                                                    --                                               --
--[[ Check if any automation items are selected on any envelope ]]                                                                                                                                    --                                               --
--[[============================================================]]--=========================================================]]--                                                                     --                                               --
                                                                                                                               --                                                                     --                                               --
function anySelectedAutomationItems()                                                                                          --                                                                     --                                               --
                                                                                                                               --                                                                     --                                               --
    for count_track = 0, r.CountTracks(0)-1 do                                                                                 --                                                                     --                                               --
                                                                                                                               --                                                                     --                                               --
        local get_track = r.GetTrack(0, count_track)                                                                           --                                                                     --                                               --
                                                                                                                               --                                                                     --                                               --
        for count_track_envelopes = 0, r.CountTrackEnvelopes(get_track)-1 do                                                   --                                                                     --                                               --
                                                                                                                               --                                                                     --                                               --
            local get_track_envelopes = r.GetTrackEnvelope(get_track, count_track_envelopes)                                   --                                                                     --                                               --
                                                                                                                               --                                                                     --                                               --
            for count_automation_items = 0, r.CountAutomationItems(get_track_envelopes)-1 do                                   --                                                                     --                                               --
                                                                                                                               --                                                                     --                                               --
                if r.GetSetAutomationItemInfo(get_track_envelopes, count_automation_items, "D_UISEL", 0, false) == 1 then      --                                                                     --                                               --
                                                                                                                               --                                                                     --                                               --
                    return true                                                                                                --                                                                     --                                               --
                                                                                                                               --                                                                     --                                               --
                end                                                                                                            --                                                                     --                                               --
            end                                                                                                                --                                                                     --                                               --
        end                                                                                                                    --                                                                     --                                               --
    end                                                                                                                        --                                                                     --                                               --
                                                                                                                               --                                                                     --                                               --
    return false                                                                                                               --                                                                     --                                               --
end                                                                                                                            --                                                                     --                                               --
                                                                                                                               --                                                                     --                                               --
--[[=========================================================================================================================]]--                                                                     --                                               --
                                                                                                                                                                                                      --                                               --
                                                                                                                                                                                                      --                                               --
                                                                                                                                                                                                      --                                               --
                                                                                                                                                                                                      --                                               --
--[[=========================================================]]                                                                                                                                       --                                               --
--[[Check if any envelope points are selected on any envelope]]                                                                                                                                       --                                               --
--[[=========================================================]]--====================================================--                                                                               --                                               --
                                                                                                                     --                                                                               --                                               --
function anySelectedEnvelopePoints()                                                                                 --                                                                               --                                               --
                                                                                                                     --                                                                               --                                               --
    for count_track = 0, r.CountTracks(0)-1 do                                                                       --                                                                               --                                               --
                                                                                                                     --                                                                               --                                               --
        local get_track = r.GetTrack(0, count_track)                                                                 --                                                                               --                                               --
                                                                                                                     --                                                                               --                                               --
        for count_track_envelopes = 0, r.CountTrackEnvelopes(get_track)-1 do                                         --                                                                               --                                               --
                                                                                                                     --                                                                               --                                               --
            local get_track_envelopes = r.GetTrackEnvelope(get_track, count_track_envelopes)                         --                                                                               --                                               --
                                                                                                                     --                                                                               --                                               --
            for count_envelope_points = 0, r.CountEnvelopePoints(get_track_envelopes)-1 do                           --                                                                               --                                               --
                                                                                                                     --                                                                               --                                               --
                local _, _, _, _, _, selected = r.GetEnvelopePoint(get_track_envelopes, count_envelope_points)       --                                                                               --                                               --
                                                                                                                     --                                                                               --                                               --
                if selected ~= 1 then                                                                                --                                                                               --                                               --
                                                                                                                     --                                                                               --                                               --
                    return true                                                                                      --                                                                               --                                               --
                                                                                                                     --                                                                               --                                               --
                end                                                                                                  --                                                                               --                                               --
            end                                                                                                      --                                                                               --                                               --
        end                                                                                                          --                                                                               --                                               --
    end                                                                                                              --                                                                               --                                               --
                                                                                                                     --                                                                               --                                               --
    return false                                                                                                     --                                                                               --                                               --
end                                                                                                                  --                                                                               --                                               --
                                                                                                                     --                                                                               --                                               --
--[[=================================================================================================================--                                                                               --                                               --
                                                                                                                                                                                                      --                                               --
--[[================================================================================================================================================================================================]]--                                               --
                                                                                                                                                                                                                                                       --
                                                                                                                                                                                                                                                       --
                                                                                                                                                                                                                                                       --
                                                                                                                                                                                                                                                       --
--[[=========================]]--                                                                                                                                                                                                                      --
                               --                                                                                                                                                                                                                      --
function Dynamic_Hotkeys()     --                                                                                                                                                                                                                      --
                               --                                                                                                                                                                                                                      --
--[[========================================================================================================================]]--                                                                                                                       --
                                                                                                                              --                                                                                                                       --
    local function action(id) r.Main_OnCommand(id, 0) end                                                                     --                                                                                                                       --
    local count_selected_items = r.CountSelectedMediaItems(0)                                                                 --                                                                                                                       --
    local window, segment, details = r.BR_GetMouseCursorContext()                                                             --                                                                                                                       --
                                                                                                                              --                                                                                                                       --
    --[Native Actions Variables]----------------------------------------------------------------                              --                                                                                                                       --
    local move_items_or_envelope_points_up = 40117                                                                            --                                                                                                                       --
    local move_envelope_points_up = 41180                                                                                     --                                                                                                                       --
    local volume_gain_plus = 41927                                                                                            --                                                                                                                       --
                                                                                                                              --                                                                                                                       --
    --[Script Actions Variables]----------------------------------------------------------------                              --                                                                                                                       --
    local pan_items_left = r.NamedCommandLookup("_RS842043b3893f85a23d3efaa9be4cae17a241688a")                           --                                                                                                                       --
    local duplicate_items_up = r.NamedCommandLookup("_RS08a4d23696de561ac7a46b8a3b3fab6a496e34e7")                           --                                                                                                                       --
    --------------------------------------------------------------------------------------------                              --                                                                                                                       --
                                                                                                                              --                                                                                                                       --
--[===========================]--                                                                                             --                                                                                                                       --
                               --                                                                                             --                                                                                                                       --
    if window == 'ruler' then  --                                                                                             --                                                                                                                       --
                               --                                                                                             --                                                                                                                       --
        return                 --                                                                                             --                                                                                                                       --
                               --                                                                                             --                                                                                                                       --
--[===========================]--                                                                                             --                                                                                                                       --
                                                                                                                              --                                                                                                                       --
                                                                                                                              --                                                                                                                       --
--[=================================]--                                                                                       --                                                                                                                       --
                                     --                                                                                       --                                                                                                                       --
    elseif window == 'tcp' then      --                                                                                       --                                                                                                                       --
                                     --                                                                                       --                                                                                                                       --
        return -- action(move_track_previous)  --                                                                                       --                                                                                                                       --
                                     --                                                                                       --                                                                                                                       --
--[=================================]--                                                                                       --                                                                                                                       --
                                                                                                                              --                                                                                                                       --
                                                                                                                              --                                                                                                                       --
--[=============================================================]--                                                           --                                                                                                                       --
                                                                 --                                                           --                                                                                                                       --
    elseif segment == 'envelope' then                            --                                                           --                                                                                                                       --
                                                                 --                                                           --                                                                                                                       --
        --[==============================================]--     --                                                           --                                                                                                                       --
                                                          --     --                                                           --                                                                                                                       --
        if anySelectedAutomationItems() then              --     --                                                           --                                                                                                                       --
                                                          --     --                                                           --                                                                                                                       --
            return -- action(move_automation_item)                  --     --                                                           --                                                                                                                       --
                                                          --     --                                                           --                                                                                                                       --
        --[==============================================]--     --                                                           --                                                                                                                       --
                                                                 --                                                           --                                                                                                                       --
        --[==============================================]--     --                                                           --                                                                                                                       --
                                                          --     --                                                           --                                                                                                                       --
        elseif anySelectedEnvelopePoints() then           --     --                                                           --                                                                                                                       --
                                                          --     --                                                           --                                                                                                                       --
            return -- action(move_envelope_points_up)               --     --                                                           --                                                                                                                       --
                                                          --     --                                                           --                                                                                                                       --
        --[==============================================]--     --                                                           --                                                                                                                       --
                                                                 --                                                           --                                                                                                                       --
        --[==============================================]--     --                                                           --                                                                                                                       --
                                                          --     --                                                           --                                                                                                                       --
        else                                              --     --                                                           --                                                                                                                       --
                                                          --     --                                                           --                                                                                                                       --
            return                                        --     --                                                           --                                                                                                                       --
                                                          --     --                                                           --                                                                                                                       --
        end                                               --     --                                                           --                                                                                                                       --
                                                          --     --                                                           --                                                                                                                       --
        --[==============================================]--     --                                                           --                                                                                                                       --
                                                                 --                                                           --                                                                                                                       --
--[=============================================================]--                                                           --                                                                                                                       --
                                                                                                                              --                                                                                                                       --
                                                                                                                              --                                                                                                                       --
--[==================================================================]--                                                      --                                                                                                                       --
                                                                      --                                                      --                                                                                                                       --
    elseif count_selected_items > 0 and details == 'item' then        --                                                      --                                                                                                                       --
                                                                      --                                                      --                                                                                                                       --
        local item = r.BR_GetMouseCursorContext_Item()                --                                                      --                                                                                                                       --
        local over_selected_item = r.IsMediaItemSelected(item, 0)     --                                                      --                                                                                                                       --
                                                                      --                                                      --                                                                                                                       --
        --[======================================================]--  --                                                      --                                                                                                                       --
                                                                  --  --                                                      --                                                                                                                       --
        if over_selected_item then                                --  --                                                      --                                                                                                                       --
                                                                  --  --                                                      --                                                                                                                       --
            action(pan_items_left)                              --  --                                                      --                                                                                                                       --
                                                                  --  --                                                      --                                                                                                                       --
        --[======================================================]--  --                                                      --                                                                                                                       --
                                                                      --                                                      --                                                                                                                       --
        --[======================================================]--  --                                                      --                                                                                                                       --
                                                                  --  --                                                      --                                                                                                                       --
        else                                                      --  --                                                      --                                                                                                                       --
                                                                  --  --                                                      --                                                                                                                       --
            return                                                --  --                                                      --                                                                                                                       --
                                                                  --  --                                                      --                                                                                                                       --
        end                                                       --  --                                                      --                                                                                                                       --
                                                                  --  --                                                      --                                                                                                                       --
        --[======================================================]--  --                                                      --                                                                                                                       --
                                                                      --                                                      --                                                                                                                       --
                                                                      --                                                      --                                                                                                                       --
--[==================================================================]--                                                      --                                                                                                                       --
                                                                                                                              --                                                                                                                       --
                                                                                                                              --                                                                                                                       --
--[=====================================================================]--                                                   --                                                                                                                       --
                                                                         --                                                   --                                                                                                                       --
    elseif window == 'arrange' then                                      --                                                   --                                                                                                                       --
                                                                         --                                                   --                                                                                                                       --
        --[=========================================================]--  --                                                   --                                                                                                                       --
                                                                     --  --                                                   --                                                                                                                       --
        if count_selected_items > 0 then                             --  --                                                   --                                                                                                                       --
                                                                     --  --                                                   --                                                                                                                       --
            action(duplicate_items_up)                 --  --                                                   --                                                                                                                       --
                                                                     --  --                                                   --                                                                                                                       --
        --[=========================================================]--  --                                                   --                                                                                                                       --
                                                                         --                                                   --                                                                                                                       --
--[=====================================================================]--                                                   --                                                                                                                       --
                                                                                                                              --                                                                                                                       --
                                                                                                                              --                                                                                                                       --
--[==================================================================]--                                                      --                                                                                                                       --
                                                                      --                                                      --                                                                                                                       --
    else                                                              --                                                      --                                                                                                                       --
                                                                      --                                                      --                                                                                                                       --
        return -- action(previous_track)                                        --                                                      --                                                                                                                       --
                                                                      --                                                      --                                                                                                                       --
    end                                                               --                                                      --                                                                                                                       --
                                                                      --                                                      --                                                                                                                       --
--[==================================================================]--                                                      --                                                                                                                       --
                                                                                                                              --                                                                                                                       --
end                                                                                                                           --                                                                                                                       --
                                                                                                                              --                                                                                                                       --
--[============]--                                                                                                            --                                                                                                                       --
                --                                                                                                            --                                                                                                                       --
blank()         --                                                                                                            --                                                                                                                       --
                --                                                                                                            --                                                                                                                       --
end             --                                                                                                            --                                                                                                                       --
                --                                                                                                            --                                                                                                                       --
--[============]--                                                                                                            --                                                                                                                       --
                                                                                                                              --                                                                                                                       --
--[[========================================================================================================================]]--                                                                                                                       --
                                                                                                                                                                                                                                                       --
--[[========================================================================================================================]]--                                                                                                                       --
                                                                                                                              --                                                                                                                       --
r.Undo_BeginBlock()                                                                                                           --                                                                                                                       --
                                                                                                                              --                                                                                                                       --
Dynamic_Hotkeys()                                                                                                             --                                                                                                                       --
                                                                                                                              --                                                                                                                       --
r.UpdateArrange()                                                                                                             --                                                                                                                       --
r.Undo_EndBlock('Dynamic Hotkeys - up', 2)                                                                                    --                                                                                                                       --
                                                                                                                              --                                                                                                                       --
--[[========================================================================================================================]]--                                                                                                                       --
                                                                                                                                                                                                                                                       --
--[===================================================================================================================================================================================================================================================]--                                                                                                                                                                                                                                                                           