--  @description: Reaper Studio - Automation Items Bundle
--  @version: 1.0
--  @author: BIXIDOX
--  @metapackage
--  @changelog:
--   + Yeah, I did that.
--  @about:
--  * Testing, I did that.
--  @provides:
--      [main] Arrange View\Automation Item\Adjustment\Reaper Studio - Automation Items - Adjustment - Length - End - Extend - Grid.lua
--      [main] Arrange View\Automation Item\Adjustment\Reaper Studio - Automation Items - Adjustment - Length - End - Shorten - Grid.lua
--      [main] Arrange View\Automation Item\Adjustment\Reaper Studio - Automation Items - Adjustment - Length - Start - Extend - Grid.lua
--      [main] Arrange View\Automation Item\Adjustment\Reaper Studio - Automation items - Adjustment - Length - Start - Shorten - Grid.lua
--      [main] Arrange View\Automation Item\Adjustment\Reaper Studio - Automation Items - Adjustment - Position - Left - Grid.lua
--      [main] Arrange View\Automation Item\Adjustment\Reaper Studio - Automation Items - Adjustment - Position - Right - Grid.lua
--  @link: https://github.com/BIXI4DOX/Reaper_Studio
